# Auto-generated by scripts/regen_schema.py — do not edit manually.
# Regenerate with: make regen-schema   (in ska-src-chat)

_TAP_OBSCORE_SCHEMA = """\
ivoa.ObsCore (alias: oc)  — primary interface — standardized flat view over CAOM2 (use this for most queries)
  obs_publisher_did  char           - publisher dataset identifier
  obs_collection     char           - short name for the data colection
  facility_name      char           - telescope name
  instrument_name    char           - instrument name
  target_name        char           - name of intended target
  obs_id             char           - internal dataset identifier
  obs_creator_did    char           - creator dataset identifier
  obs_release_date   char           - timestamp of date the data becomes publicly available
  dataproduct_type   char           - type of product
  calib_level        int            - calibration level (0,1,2,3)
  access_url         char           - URL to download the data
  access_format      char           - format of the data file(s)
  access_estsize     long           - estimated size of the download
  s_ra               double         - RA of central coordinates
  s_dec              double         - DEC of central coordinates
  s_fov              double         - size of the region covered
  s_fov_min          double         - min size of the region covered (e.g. at all energies)
  s_region           char           - region bounded by observation
  s_resolution       double         - typical spatial resolution
  s_resolution_min   double         - smallest spatial resolution
  s_resolution_max   double         - largest spatial resolution
  s_xel1             long           - dimensions (number of pixels) along one spatial axis
  s_xel2             long           - dimensions (number of pixels) along the other spatial axis
  em_min             double         - start spectral coordinate value
  em_max             double         - stop spectral coordinate value
  em_res_power       double         - typical spectral resolution
  em_resolution      double         - typical spectral resolution
  em_resolution_min  double         - minimum spectral resolution
  em_resolution_max  double         - maximum spectral resolution
  em_xel             long           - dimensions (number of pixels) along the energy axis
  em_ucd             char           - UCD describing the spectral axis
  t_min              double         - start time of observation (MJD)
  t_max              double         - end time of observation (MJD)
  t_exptime          double         - typical exposure time
  t_exptime_min      double         - minimum exposure time
  t_exptime_max      double         - maximum exposure time
  t_resolution       double         - typical temporal resolution
  t_xel              long           - dimensions (number of pixels) along the time axis
  pol_states         char           - polarization states present in the data
  pol_xel            long           - dimensions (number of pixels) along the polarization axis
  o_ucd              char           - UCD describing the observable axis (pixel values)
  lastModified       char           - timestamp of last modification of the metadata

ivoa.ObsCore_radio (alias: ocr)  — radio extension — 1:1 with ivoa.ObsCore
  JOIN: JOIN ivoa.ObsCore_radio AS ocr ON ocr.obs_publisher_did = oc.obs_publisher_did
  s_largest_angular_scale_min  double         - minimum largest angular scale that is recoverable in the data
  s_largest_angular_scale_max  double         - maximum minimum largest angular scale that is recoverable in the data
  uv_distance_min              double         - minimum distance in the UV plane
  uv_distance_max              double         - maximum distance in the UV plane
  uv_distribution_ecc          double         - eccentricity of the UV distribution
  uv_distribution_fill         double         - filling factor of UV distribution
  obs_publisher_did            char           - natural join key

caom2.Observation (alias: o)  — base CAOM2 observation record
  uri                         char           - unique URI for this observation
  uriBucket                   char           - short hex string
  collection                  char           - data collection this observation belongs to
  algorithm_name              char           - algorithm that defines the observation( exposure for simple, grouping algorithm for composites)
  obstype                     char           - type of data collected (e.g. FITS OBSTYPE header)
  intent                      char           - intended purpose of data (one of: science, calibration)
  sequenceNumber              int            - sequence number assigned by the observatory
  metaRelease                 char           - date the metadata for an observation is public (UTC)
  metaReadGroups              char           - GMS groups that are authorized to see metadata
  proposal_id                 char           - collection-specific unique proposal identifier
  proposal_pi                 char           - proposal principal investigator
  proposal_project            char           - project that created/acquired the observation
  proposal_title              char           - proposal title
  proposal_keywords           char           - proposal keywords (separated by |)
  proposal_reference          char           - reference to external proposal info [new in 2.5]
  target_name                 char           - name of intended target
  target_targetID             char           - identifier of intended target [new in 2.4]
  target_type                 char           - classification of intended target
  target_standard             int            - intended target is a standard (0=false, 1=true)
  target_redshift             double         - redshift of intended target
  target_moving               int            - flag for moving target
  target_keywords             char           - target keywords (separated by |)
  targetPosition_coordsys     char           - coordinate system for target position
  targetPosition_coordinates  double         - intended position to observe
  targetPosition_equinox      double         - equinox of target position coordinate system
  telescope_name              char           - name of telescope used to acquire observation
  telescope_geoLocationX      double         - x component of geocentric location of telescope
  telescope_geoLocationY      double         - y component of geocentric location of telescope
  telescope_geoLocationZ      double         - z component of geocentric location of telescope
  telescope_keywords          char           - telescope keywords (separated by |)
  requirements_flag           char           - flag describing satisfied proposal requirements (possible values: fail)
  telescope_trackingMode      char           - telescope tracking mode [new in 2.5]
  instrument_name             char           - name of instrument used to acquire observation
  instrument_keywords         char           - instrument keywords (separated by |)
  environment_seeing          double         - atmospheric seeing (FWHM)
  environment_humidity        double         - humidity at telescope during observation
  environment_elevation       double         - elevation above horizon (0 to 90)
  environment_tau             double         - zenith optical depth
  environment_wavelengthTau   double         - wavelength at which Tau has been measured
  environment_ambientTemp     double         - ambient temperature telescope during observation
  environment_photometric     int            - conditions were photometric (0=false, 1=true)
  members                     char           - members of a composite observation (space-separated list of Observation URIs)
  typeCode                    char           - single character code to denote type: S(impleObservation) or D(erivedOvservation)
  obsID                       char           - primary key
  metaProducer                char           - identifier for the producer of this entity metadata (URI of the form {organisation}:{software}-{version}) [new in 2.4]
  lastModified                char           - timestamp of last modification of this row
  maxLastModified             char           - timestamp of last modification of this entity+children
  metaChecksum                char           - checksum of the metadata in this entity (URI of the form {algorithm}:{hex value})
  accMetaChecksum             char           - checksum of the metadata in this entity+children (URI of the form {algorithm}:{hex value})

caom2.Plane (alias: p)  — 1:N with caom2.Observation — science data per calibration level
  JOIN: JOIN caom2.Plane AS p ON p.obsID = o.obsID
  publisherID                   char           - unique publisher identifier for this product
  obsID                         char           - foreign key
  uri                           char           - unique internal URI for this product
  metaRelease                   char           - date the metadata for a plane is public (UTC)
  metaReadGroups                char           - GMS groups that are authorized to see metadata [new in 2.4]
  dataRelease                   char           - date the data for a plane is public (UTC)
  dataReadGroups                char           - GMS groups that are authorized to see data [new in 2.4]
  dataProductType               char           - IVOA ObsCore data product type + extensions
  calibrationLevel              int            - IVOA ObsCore calibration level + extensions (-1,0,1,2,3,4)
  provenance_name               char           - name of the process that created this plane
  provenance_version            char           - version of the process/software
  provenance_reference          char           - external reference (URL)
  provenance_producer           char           - responsible entity (e.g. person)
  provenance_project            char           - responsible entity (e.g. person)
  provenance_runID              char           - responsible entity (e.g. person)
  provenance_lastExecuted       char           - date this process was last executed
  provenance_keywords           char           - provenance keywords (separated by |)
  provenance_inputs             char           - inputs of the process that created this plane (space-separated list of Plane URIs)
  metrics_sourceNumberDensity   double         - number density of sources
  metrics_background            double         - background intensity
  metrics_backgroundStddev      double         - standard deviation in background
  metrics_fluxDensityLimit      double         - flux density limit where S:N=5 for point source
  metrics_magLimit              double         - AB magnitude limit where S:N=5 for point source
  observable_ucd                char           - UCD (Universal Content Descriptor) for the observed/measure quantity
  observable_calibration        char           - calibration status of the observed/measure quantity [new in 2.5]
  quality_flag                  char           - flag describing the data quality (possible values: junk)
  position_bounds               char           - queryable positional coverage of the data
  position_samples              char           - detailed positional coverage of the data
  position_minBounds            char           - queryable minimum positional coverage... TBD [new in 2.5]
  position_dimension            long           - dimensions (number of pixels) along the spatial axes
  position_maxRecoverableScale  double         - TBD [new in 2.5]
  position_resolution           double         - median spatial resolution (FWHM)
  position_resolutionBounds     double         - range of median spatial resolution (FWHM)
  position_calibration          char           - calibration of the position metadata (astrometry) [new in 2.5]
  position_sampleSize           double         - median sample (pixel) size on spatial axes
  energy_bounds                 double         - queryable energy coverage
  energy_samples                double         - detailed energy coverage
  energy_dimension              long           - dimension (number of pixels) along energy axis
  energy_resolvingPowerBounds   double         - range of relative energy resolution (R)
  energy_resolution             double         - representative absolute energy resolution
  energy_resolvingPower         double         - representative relative energy resolution aka resolving power (R)
  energy_resolutionBounds       double         - range of absolute energy resolution
  energy_sampleSize             double         - representative sample (pixel) size on energy axis
  energy_rest                   double         - rest energy of target spectral feature
  energy_bandpassName           char           - collection-specific name for energy band (e.g. filter name)
  energy_energyBands            char           - energy band names (Radio,Millimeter,Infrared,Optical,UV,EUV,X-ray,Gamma-ray), separated by |
  energy_calibration            char           - calibration of the energy axis
  energy_transition_species     char           - atom or molecule
  energy_transition_transition  char           - specific energy transition of species
  time_bounds                   double         - time coverage (Modified Julian Day)
  time_samples                  double         - detailed time coverage (Modified Julian Day)
  time_dimension                long           - dimension (number of pixels) along time axis
  time_resolution               double         - median resolution on the time axis
  time_exposureBounds           double         - range of exposure on the time axis [new in 2.4]
  time_resolutionBounds         double         - range of resolution on the time axis [new in 2.4]
  time_sampleSize               double         - median sample (pixel) size on time axis
  time_calibration              char           - calibration of the time axis
  time_exposure                 double         - representative exposure time (mean per pixel?)
  polarization_states           char           - polarization letter codes in canonical order, separated by /
  polarization_dimension        int            - number of samples (pixels) along polarization axis
  custom_ctype                  char           - coordinate type for custom axis
  custom_bounds                 double         - queryable custom axis coverage
  custom_samples                double         - detailed custom axis coverage
  custom_dimension              long           - dimension (number of pixels) along custom axis
  uv_distance                   double         - UV plane coverage
  uv_distributionEccentricity   double         - TBD [new in 2.5]
  uv_distributionFill           double         - TBD [new in 2.5]
  planeID                       char           - unique plane identifier
  metaProducer                  char           - identifier for the producer of this entity metadata (URI of the form {organisation}:{software}-{version}) [new in 2.4]
  lastModified                  char           - timestamp of last modification of this row
  maxLastModified               char           - timestamp of last modification of this entity+children
  metaChecksum                  char           - checksum of the metadata in this entity (URI of the form {algorithm}:{hex value})
  accMetaChecksum               char           - checksum of the metadata in this entity+children (URI of the form {algorithm}:{hex value})

caom2.Artifact (alias: a)  — 1:N with caom2.Plane — individual data files
  JOIN: JOIN caom2.Artifact AS a ON a.planeID = p.planeID
  uri                char           - external URI for the physical artifact
  planeID            char           - foreign key
  uriBucket          char           - short hex string
  productType        char           - product type (science, calibration, auxiliary, preview, info)
  releaseType        char           - release type (data, meta)
  contentType        char           - content-type of the representation at uri
  contentLength      long           - size of the representation at uri
  contentChecksum    char           - checksum of the content (URI of the form {algorithm}:{hex value})
  contentRelease     char           - date the data for an artifact is public (UTC) (default: inherit from Plane) [new in 2.4]
  contentReadGroups  char           - GMS groups that are authorized to retrieve the artifact (default: inherit from Plane) [new in 2.4]
  descriptionID      char           - reference to an ArtifactDescription [new in 2.5]
  artifactID         char           - primary key
  metaProducer       char           - identifier for the producer of this entity metadata (URI of the form {organisation}:{software}-{version}) [new in 2.4]
  lastModified       char           - timestamp of last modification of this row
  maxLastModified    char           - timestamp of last modification of this entity+children
  metaChecksum       char           - checksum of the metadata in this entity (URI of the form {algorithm}:{hex value})
  accMetaChecksum    char           - checksum of the metadata in this entity+children (URI of the form {algorithm}:{hex value})
"""

_SDM_SCHEMA = """\
sdm.software (alias: s)  — base table
  changelog     char           - Summary of changes for this version
  description   char           - Long-form software description
  id            int            - Internal primary key
  release_date  char           - Release timestamp
  status        char           - Uppercase enum: ALPHA, BETA, TESTING, STABLE, DEPRECATED — e.g. s.status = 'STABLE'
  uri           char           - Unique software URI format: <publisher>:<name>:<version>

sdm.resource_requirements (alias: r)  — 1:1 with software
  JOIN: LEFT JOIN sdm.resource_requirements AS r ON r.software_id = s.id
  id                  int            - Primary key
  min_memory          int            - Minimum memory required (MB)
  recommended_memory  int            - Recommended memory (MB)
  requires_gpu        boolean        - Boolean stored as string — ADQL: r.requires_gpu = 'true' or r.requires_gpu = 'false'
  software_id         int            - FK to software

sdm.artifact (alias: a)  — 1:N with software
  JOIN: JOIN sdm.artifact AS a ON a.software_id = s.id
  cpu_architecture  char           - Supported CPU architectures
  digest            char           - Artifact digest for integrity verification
  entrypoint        char           - Execution entrypoint
  id                int            - Primary key
  kind              char           - Uppercase enum: DOCKER, OCI, SINGULARITY — e.g. a.kind = 'DOCKER'
  location          char           - Artifact location (URI/path)
  software_id       int            - FK to software
  supported_modes   char           - Supported execution modes

sdm.discovery_science_category (alias: dsc)  — reach via sdm.discovery bridge
  JOIN: JOIN sdm.discovery AS d ON d.software_id = s.id
  JOIN: JOIN sdm.discovery_science_category AS dsc ON dsc.discovery_id = d.id
  category      char           - Case-sensitive string. Known values (use exact case): 'radio-astronomy', 'pulsar-research', 'image-analysis', 'data-processing', 'Radio Astronomy', 'Image Analysis', 'Source Detection', 'EoR Science', 'Systematics Analysis', 'Test' — e.g. dsc.category = 'radio-astronomy'
  discovery_id  int            - FK to discovery
  id            int            - Primary key

sdm.discovery_function_category (alias: dfc)  — reach via sdm.discovery bridge
  JOIN: JOIN sdm.discovery AS d ON d.software_id = s.id
  JOIN: JOIN sdm.discovery_function_category AS dfc ON dfc.discovery_id = d.id
  category      char           - Case-sensitive string. Known values (use exact case): 'imaging', 'calibration', 'flagging', 'analysis', 'astrometry', 'source-finding', 'pulsar-search', 'pulsar-timing', 'pulsar-analysis', 'polarimetry', 'mcmc', 'periodicity-search', 'table-operations', 'timing', 'Source Finding', 'Catalog Generation', 'Gaussian Fitting', 'Image Decomposition', 'Power Spectrum Estimation', 'Quality Assessment', 'Testing' — e.g. dfc.category = 'imaging'
  discovery_id  int            - FK to discovery
  id            int            - Primary key

sdm.discovery_science_working_group (alias: dswg)  — reach via sdm.discovery bridge
  JOIN: JOIN sdm.discovery AS d ON d.software_id = s.id
  JOIN: JOIN sdm.discovery_science_working_group AS dswg ON dswg.discovery_id = d.id
  discovery_id   int            - FK to discovery
  id             int            - Primary key
  working_group  char           - Science working group name string — e.g. swg.working_group = 'VLBI'
"""

_TAP_MERMAID = """\
erDiagram
    IVOA_OBSCORE {
        string obs_publisher_did
        string obs_collection
        string facility_name
        string instrument_name
        string target_name
        string obs_id
        string dataproduct_type
        int calib_level
        float s_ra
        float s_dec
        float s_fov
        float t_min
        float t_max
        string access_url
    }
    IVOA_OBSCORE_RADIO {
        string obs_publisher_did FK
        float uv_distance_min
        float uv_distance_max
        float s_largest_angular_scale_min
        float uv_distribution_fill
    }
    CAOM2_OBSERVATION {
        string obsID PK
        string uri
        string collection
        string instrument_name
        string target_name
        string telescope_name
        string algorithm_name
        string intent
    }
    CAOM2_PLANE {
        string planeID PK
        string obsID FK
        string publisherID
        string dataProductType
        int calibrationLevel
        string position_bounds
        float energy_bounds
        float time_bounds
        float time_exposure
    }
    CAOM2_ARTIFACT {
        string artifactID PK
        string planeID FK
        string uri
        string productType
        string contentType
        bigint contentLength
    }

    IVOA_OBSCORE ||--o| IVOA_OBSCORE_RADIO : "radio extension"
    CAOM2_OBSERVATION ||--o{ CAOM2_PLANE : "contains planes"
    CAOM2_PLANE ||--o{ CAOM2_ARTIFACT : "contains artifacts"
"""

_SDM_MERMAID = """\
erDiagram
    SDM_ARTIFACT {
        string cpu_architecture
        string digest
        string entrypoint
        int id PK
        string kind
        string location
        int software_id FK
        string supported_modes
    }
    SDM_DATA_COMPATIBILITY {
        int id PK
        int software_id FK
    }
    SDM_DATA_INPUT_TYPE {
        int data_compatibility_id FK
        int id PK
        string input_type
    }
    SDM_DATA_OUTPUT_TYPE {
        int data_compatibility_id FK
        int id PK
        string output_type
    }
    SDM_DISCOVERY {
        int id PK
        int software_id FK
    }
    SDM_DISCOVERY_FUNCTION_CATEGORY {
        string category
        int discovery_id FK
        int id PK
    }
    SDM_DISCOVERY_SCIENCE_CATEGORY {
        string category
        int discovery_id FK
        int id PK
    }
    SDM_DISCOVERY_SCIENCE_WORKING_GROUP {
        int discovery_id FK
        int id PK
        string working_group
    }
    SDM_DISCOVERY_TOOLS_INCLUDED {
        int discovery_id FK
        int id PK
        string tool_name
    }
    SDM_PROVENANCE {
        int id PK
        string registered_by
        string registration_date
        string repository_url
        int software_id FK
    }
    SDM_RESOURCE_REQUIREMENTS {
        int id PK
        int min_memory
        int recommended_memory
        boolean requires_gpu
        int software_id FK
    }
    SDM_SOFTWARE {
        string changelog
        string description
        int id PK
        string release_date
        string status
        string uri
    }

    SDM_SOFTWARE ||--o| SDM_RESOURCE_REQUIREMENTS : "has requirements"
    SDM_SOFTWARE ||--o{ SDM_ARTIFACT : "has artifacts"
    SDM_SOFTWARE ||--o{ SDM_DISCOVERY : "has discovery"
    SDM_DISCOVERY ||--o{ SDM_DISCOVERY_SCIENCE_CATEGORY : "science categories"
    SDM_DISCOVERY ||--o{ SDM_DISCOVERY_FUNCTION_CATEGORY : "function categories"
    SDM_DISCOVERY ||--o{ SDM_DISCOVERY_SCIENCE_WORKING_GROUP : "working groups"
"""
