name: CI-crontests

on:
  push:
    # Run this job on release tags, but not on pushes to the main branch
    tags:
    - '*'
  schedule:
    # run every Friday at 23:00 UTC
    - cron: '0 23 * * 5'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    if: github.repository == 'astropy/astroquery'
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: py3.11 all dev deps online
            os: ubuntu-latest
            python: '3.11'
            toxenv: py311-test-alldeps-devdeps-online
            toxargs: -v
            toxposargs: -v --durations=50

          - name: Windows py3.9 all deps online
            os: windows-latest
            python: '3.9'
            toxenv: py39-test-alldeps-online
            toxargs: -v
            toxposargs: -v --durations=50

          - name: py3.11 pre-release all deps
            os: ubuntu-latest
            python: '3.11'
            toxenv: py311-test-alldeps-predeps
            toxargs: -v
            toxposargs: -v

          - name: Documentation build with linkcheck
            os: ubuntu-latest
            python: '3.10'
            toxenv: linkcheck

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install Python dependencies
      run: python -m pip install --upgrade tox
    - name: Run tests
      run: tox ${{ matrix.toxargs }} -e ${{ matrix.toxenv }} -- ${{ matrix.toxposargs }}
